# Generated by Django 4.2.15 on 2024-09-06 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_recipeingridient_ingridient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingridient',
            name='ingridient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_ingridients', to='recipes.ingridient', verbose_name='Ингридиент'),
        ),
    ]
